---
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: test
  image: docker:dind
  volumes:
  - name: docker.sock
    path: /var/run
  commands:
    - sleep 5 # give docker enough time to start
    - docker ps -a

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
    - name: docker.sock
      path: /var/run